### ISSUE TITLE
Update wkhtmltopdf module to take new Qt upgrade into account

### ISSUE THREAD

**Issue by mattr-** [boxen/puppet-wkhtmltopdf#2]
Since the Qt module has been fixed for Mavericks, it would be awesome if we could get the same update for wkhtmltopdf.

I'll see if I can't get to it at some point in the next few days, but wanted to log a placeholder here.

**Comment by dgoodlad** [comment]
Figured since I did the legwork on the qt module I'd jump in and take care of this one too :smile_cat:

I've released 1.2.0, give that a try!

**Comment by mattr-** [comment]
Thanks! :heart:

I’ll give it a shot here in the next few days!

**Comment by mattr-** [comment]
I remember trying this at one point and having it work, so now (better late than never, right?) I'll go ahead and close this one out. :smiley:
